# ======================================================
# SERVER CONFIG
# ======================================================
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/expensetrackerDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true


spring.jpa.properties.hibernate.format_sql=true

# Tells Hibernate to use PostgreSQL-specific SQL dialect (data types, functions etc.)
# Without this, Hibernate might generate ANSI SQL that doesn't use Postgres features.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ======================================================
# JACKSON (JSON serialization config)
# ======================================================

# By default, Jackson serializes LocalDate as an array [2025,3,15].
# This setting makes it write it as a readable string "2025-03-15" instead.
spring.jackson.serialization.write-dates-as-timestamps=false

# ======================================================
# SPRINGDOC / SWAGGER
# ======================================================
# Where the Swagger UI will be available: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html

# Where the raw OpenAPI JSON spec lives: http://localhost:8080/api-docs
springdoc.api-docs.path=/api-docs